config/routes.rb
Rails.application.routes.draw do

  root   'sessions#new'

  get    '/signup',  to: 'users#new'
  get    '/profile', to: 'users#show'
  get    '/profile/edit', to: 'users#edit'
  get    '/matching',to: 'matchings#index'
  get    '/check', to: 'users#check'
  get    '/contact', to: 'static_pages#contact'
  get    '/login',   to: 'sessions#new'


  post   '/signup',  to: 'users#create'
  post   '/user/create',  to: 'users#create'
  post   '/waiting',to: 'matchings#entry'
  post   '/contact', to: 'static_pages#send_mail'
  post   '/show', to: 'static_pages#success_mail'
  post   '/login',   to: 'sessions#create'

  patch  '/user/update',  to: 'users#update'

  delete '/user/delete',   to: 'users#destroy'
  delete '/logout',        to: 'sessions#destroy'

  resources :password_resets, only: [:new, :create, :edit, :update]

  # routesに記載のないurlへのアクセスを全てリダイレクト
  get "*path" => redirect("/")

end

app/models/user.rb
class User < ApplicationRecord

  attr_accessor :remember_token, :reset_token

  has_secure_password

  belongs_to :time_zone, optional: true

  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :name,  presence: true, length: { maximum: 50 }
  validates :name, uniqueness: {
    message: Settings.user[:already_used]
  }
  validates :email, presence: true
  validates :email, uniqueness: {
    message: Settings.user[:already_used]
  }
  #validates :department_name, presence: true
  #validates :slack_id , presence: true #, uniqueness: true

  #validate :file_kind     #アップロードファイルの妥当性をfile_invalid?メソッドで検証
  #validate :over_size
  # validate :file_invalid?

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  class << self
    def new_token
      SecureRandom.urlsafe_base64
    end

    def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:edit, :show, :update, :destroy, :check]
  before_action :correct_user,   only: [:edit, :show, :update, :destroy, :check]

  def new
    @user = User.new
  end

  def show
    @user = User.find(current_user.id)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "ユーザー登録に成功しました。"
      redirect_to matching_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to profile_path
    else
      render 'edit'
    end
  end

  def check
    @pairs = User.where(pair_id: current_user.pair_id)
  end

  def destroy
    User.find(current_user.id).destroy
    flash[:success] = "ユーザーを削除しました。"
    redirect_to login_path
  end

  private

    def user_params
      params.require(:user).permit(:name,
                                   :email,
                                   :password,
                                   :password_confirmation,
                                   :department_name,
                                   :slack_id,
                                   :data
                                   )
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="col-lg-12">
  <div class="bs-component">
    <%= form_for(@user, url: yield(:url), class: 'form-horizontal') do |f| %>
      <fieldset>

        <div class="form-group">
          <%= f.label :名前, class: 'mr5' %>
          <% if controller.action_name == "new" || controller.action_name == "create" %>
            <span class="label label-danger">必須</span>
            <%= f.text_field :name, class: 'form-control', required: true %>
          <% else %>
            <%= f.text_field :name, class: 'form-control' %>
          <% end %>
        </div>

        <div class="form-group">
          <%= f.label :メールアドレス, class: 'mr5' %>
          <span class="label label-danger">必須</span>
          <%= f.email_field :email, class: 'form-control', required: true %>
        </div>

        <div class="form-group">
          <%= f.label :パスワード, class: 'mr5' %>
          <% if controller.action_name == "new" || controller.action_name == "create" %>
            <span class="label label-danger">必須</span>
            <%= f.password_field :password, class: 'form-control', required: true %>
          <% else %>
            <%= f.password_field :password, class: 'form-control' %>
          <% end %>
        </div>

        <div class="form-group">
          <%= f.label :パスワード確認, class: 'mr5' %>
          <% if controller.action_name == "new" || controller.action_name == "create" %>
            <span class="label label-danger">必須</span>
            <%= f.password_field :password_confirmation, class: 'form-control', required: true %>
          <% else %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          <% end %>
        </div>

        <div class="form-group">
          <%= f.label :部署名, class: 'mr5' %>
          <% if controller.action_name == "new" || controller.action_name == "create" %>
            <span class="label label-danger">必須</span>
            <%= f.text_field :department_name, class: 'form-control', required: true %>
          <% else %>
            <%= f.text_field :department_name, class: 'form-control' %>
          <% end %>
        </div>

        <div class="form-group">
          <%= f.label :スラックID, class: 'mr5' %>
          <% if controller.action_name == "new" || controller.action_name == "create" %>
            <span class="label label-danger">必須</span>
            <%= f.text_field :slack_id, class: 'form-control', required: true %>
          <% else %>
            <%= f.text_field :slack_id, class: 'form-control' %>
          <% end %>
        </div>
       
        <div class="form-group">
          <%= f.submit yield(:button_text), class: "btn btn-primary" %>
          <%= link_to "戻る", :back, class: "btn btn-success" %>
        </div>
        
      </fieldset>
    <% end %>
  </div>
</div>

app/views/users/check.html.erb
<% provide(:title, 'マッチング相手情報') %>
<% provide(:page_title, "マッチング相手情報") %>
<% @pairs.each do |pair| %>

  <div class="col-lg-12">
    <div class="bs-component">
      <fieldset>
        <div class="form-group">
          <label>名前</label>
          <div><%= pair.try :name  %></div>
        </div>

        <div class="form-group">
          <label>部署名</label>
          <div><%= pair.try :department_name %></div>
        </div>

        <div class="form-group">
          <label>Slack ID</label>
          <div><%= pair.try :slack_id %></div>
        </div>

        <div class="form-group">
          <label>プロフィール写真</label>
          <div><%= pair.try :profile_img %></div>
        </div>
      </fieldset>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "会員情報編集") %>
<% provide(:page_title, "会員情報編集") %>
<% provide(:button_text, '更新') %>
<% provide(:url, user_update_path) %>

<%= render 'shared/error_messages' %>
<%= render 'form' %>

app/views/users/new.html.erb
<% provide(:title, '新規会員登録') %>
<% provide(:page_title, "新規会員登録") %>
<% provide(:button_text, '登録') %>
<% provide(:url, user_create_path) %>

<%= render 'shared/error_messages' %>
<%= render 'form' %>

app/views/users/show.html.erb
<% provide(:title, '会員情報') %>
<% provide(:page_title, "会員情報") %>

<%= render 'shared/error_messages' %>

<div class="col-lg-12">
  <div class="bs-component">
    <fieldset>

      <div class="form-group">
        <label>名前</label>
        <div><%= @user.try :name %></div>
      </div>

      <div class="form-group">
        <label>メールアドレス</label>
        <div><%= @user.try :email %></div>
      </div>

      <div class="form-group">
        <label>部署名</label>
        <div><%= @user.try :department_name %></div>
      </div>

      <div class="form-group">
        <label>Slack ID</label>
        <div><%= @user.try :slack_id %></div>
      </div>

      <div class="form-group">
        <label>プロフィール写真</label>
        <div><%= @user.try :profile_img %></div>
      </div>
    </fieldset>
    <%= link_to "編集", "profile/edit", class: "btn btn-primary" %>
    <%= link_to "削除", user_delete_path, method: :delete, data: { confirm: "アカウントを削除します。本当によろしいでしょうか？" }, class: "btn btn-danger" %>
  </div>
</div>