config/routes.rb
Rails.application.routes.draw do

  root   'sessions#new'

  get    '/signup',  to: 'users#new'
  get    '/profile', to: 'users#show'
  get    '/profile/edit', to: 'users#edit'
  get    '/matching',to: 'matchings#index'
  get    '/check', to: 'users#check'
  get    '/contact', to: 'static_pages#contact'
  get    '/login',   to: 'sessions#new'


  post   '/signup',  to: 'users#create'
  post   '/user/create',  to: 'users#create'
  post   '/waiting',to: 'matchings#entry'
  post   '/contact', to: 'static_pages#send_mail'
  post   '/show', to: 'static_pages#success_mail'
  post   '/login',   to: 'sessions#create'

  patch  '/user/update',  to: 'users#update'

  delete '/user/delete',   to: 'users#destroy'
  delete '/logout',        to: 'sessions#destroy'

  resources :password_resets, only: [:new, :create, :edit, :update]

  # routesに記載のないurlへのアクセスを全てリダイレクト
  get "*path" => redirect("/")

end

app/views/layouts/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>

  <%= f.label :名前 %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :メールアドレス %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :パスワード %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :パスワード確認 %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.label :部署名 %>
  <%= f.text_field :department_name, class: 'form-control' %>

  <%= f.label :スラックID %>
  <%= f.text_field :slack_id, class: 'form-control' %>

  <%= f.label :プロフィール写真 %>
  <%= f.text_field :profile_img, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/layouts/_members_header.html.erb
<header>
  <div class="navbar navbar-default navbar-fixed-top" id="spectrumPlugin">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "シャッフルランチ", root_path, class: "navbar-brand" %>
        <% if current_user.present? %>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <% end %>
      </div>
      <% if current_user.present? %>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li <%= current_page matching_path %>><%= link_to "マッチング", matching_path %></li>
            <li <%= current_page profile_path %>><%= link_to "プロフィール", profile_path %></li>
            <li <%= current_page check_path %>><%= link_to "マッチング相手確認", check_path %></li>
            <li <%= current_page contact_path %>><%= link_to "お問い合わせ", contact_path %></li>
            <li><%= link_to "ログアウト", logout_path, method: "delete" %></li>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %> | シャッフルランチ</title>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name=”robots” content=”noindex”>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--[if lt IE 9]>
      <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>

  <body>
    <%= render 'layouts/members_header' %>
    <div class="container">
      <div class="bs-docs-section">
        <div class="row">
          <div class="col-lg-12">
            <div class="page-header">
              <h1 id="nav"><%= yield :page_title %></h1>
            </div>
          </div>

          <div id="error_explanation">
            <% flash.each do |message_type, message| %>
              <div class="col-lg-4">
                <div class="bs-component">
                  <div class="shuffle-message alert alert-dismissible alert-<%= message_type %>">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong><%= message %></strong>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
          <%= yield %>
        </div>
      </div>

    </div>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-101337153-1', 'auto');
      ga('send', 'pageview');

    </script>
  </body>
</html>